envs:
  production:
    description: "My env description"
    devices: !!inc/file dev-prod.yml
    app: scripts/app.py
  develop1:
    description: "Running directly from the stens"
    devices: !!inc/file dev-prod.yml
    app: scripts/app.py
