# ***********************************
# define spanner's configuration file
# ***********************************

# variables:
#    MY_GLOBAL_VAR: “global env variable”

# code quality options
# code_qa:
    # compulsory
#     source_dir: 'template.cpp'

# build options
build_binary:
    # compulsory
    type: 'aws esp32'
    # compulsory
    source_dir: 'esp32_devkitc_demo'
    # compulsory/optional
    variables:
      AWS_ACCESS_KEY_ID : 123
      AWS_SECRET_ACCESS_KEY : 123
      THING_NAME : 123
      WIFI_SSID : 123
      WIFI_PASSWORD : 123
      WIFI_SECURITY : 123
    # optional
    build_command: ls -la && make clean
    # optional
    binary_name:
    # optional
    pre_flight:
    # optional
    post_flight:
    # optional
    on_failure:
    # optional
    on_success:

# run options
# testing:
    # compulsory
#     source_dir: 'Scenario.py'    
    # optional
#     variables:
#         ACCESS_TOKEN: "sdasxas23"
    # optional
#     pre_flight:
    # optional
#     post_flight:
    # optional
#     on_failure:
    # optional
#     on_success:
    # optional
#     binary_update:
        # compulsory
#         platform: 'aws esp32'
#         binary: auto


# # deployment options
# deployment:
#     platform:
#     credentials:
#     target:
#     binary_url:
#     on_success:

# # pre_flight options
# pre_flight:
#     slack:

# # post_flight options
# post_flight:
#     slack:


