build_binary:
        platform: aws esp32
        source: esp32_devkitc_demo 
        build_command: las && make clean && make
        aws_credentials: creds/esp32_aws_creds.txt
        wifi_credentials: creds/esp32_wifi_creds.json
test_automation: 
       testplan: mytests.py
code_quality:
       false
deploy:  
       false
