build_binary:
        platform: particle photon
        source: example_app
        build_command: ls && make clean && make
test_automation: 
       testplan: mytests.py
code_quality:
       false
deploy:  
       false
