# code_qa:
#     type: basic

build_binary:
    type: 'aws esp32'
    source_dir: 'app'
    build_command: make
    binary_name: my_binary
    env_vars:
        - $SPN_AWS_ACCESS_KEY_ID
        - $SPN_AWS_SECRET_ACCESS_KEY
        - $SPN_ESP32_THING_NAME
        - $SPN_ESP32_WIFI_SSID
        - $SPN_ESP32_WIFI_PASSWORD
        - $SPN_ESP32_WIFI_SECURITY
testing:
    source_dir: 'Scenario.py'
    binary_update:
         devices:
            - $Memas
         env_vars:
            - $SPN_PARTICLE_ACCESS
         platform: 'particle photon'
         #binary: auto
         binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
         #binary: binary/mike_binary.bin
