# ***********************************
# define spanner's configuration file
# ***********************************

variables:
   MY_GLOBAL_VAR: “global env variable”

# code quality options
code_qa:
    # compulsory
    filename: 'template.cpp'

# build options
build_binary:
    # compulsory
    type: 'aws esp32'
    # compulsory
    source_dir: 'esp32_devkitc_demo'
    # compulsory/optional
    variables:
#         AWS_CREDS: 'creds/esp32_aws_creds.txt'
        WIFI_CREDS: 'creds/esp32_wifi_creds.json'
    # optional
    build_command:
    # optional
    binary_name:
    # optional
    pre_flight:
    # optional
    post_flight:
    # optional
    on_failure:
    # optional
    on_success:

# run options
testing:
    # compulsory
    filename: 'Scenario.py'    
    # optional
    variables:
        ACCESS_TOKEN: "sdasxas23"
    # optional
    pre_flight:
    # optional
    post_flight:
    # optional
    on_failure:
    # optional
    on_success:
    # optional
    binary_update:
        # compulsory
        platform: 'aws esp32'


# # deployment options
# deployment:
#     platform:
#     credentials:
#     target:
#     binary_url:
#     on_success:

# # pre_flight options
# pre_flight:
#     slack:

# # post_flight options
# post_flight:
#     slack:


