# # code_qa:
# #     type: basic
        
# testing:
#     source_dir: 'Scenario.py'
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#     binary_update:
#          devices:
#             - $DEVICE_1    
#          platform: 'particle photon'
#          #binary: auto
#          binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
#          #binary: binary/mike_binary.bin

pre_flight:
    - echo "Hello there"
    - echo "Over"

post_flight: 
    - echo "Post flight command"

build_binary:
    builder: 'particle photon'
    binary_name: './app/target/app.bin'
    script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/app
   
# build_binary:
#     builder: 'aws esp32'
#     #pre_flight:
#     #    - bash ./thing_config.sh
#     script: 'cd esp32_devkitc_esp_wrover_kit/make && make'
#     binary_name: 'esp32_devkitc_esp_wrover_kit/build/aws_demo.bin'
#     env_vars:
#         - $SPN_AWS_ACCESS_KEY_ID
#         - $SPN_AWS_SECRET_ACCESS_KEY
#         - $SPN_AWS_OUTPUT
#         - $SPN_AWS_REGION
       
#testing:
#    script: uartTest.py
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#     device_update:
#         devices:
#             - $DEVICE_1
#         ota_method: particle
#         binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
