build_binary:
        platform: particle photon
        source: app
        build_command: ls && make clean
test_automation: 
       testplan: mytests.py
code_quality:
       false
deploy:  
       false
