# code_qa:
#     type: basic

build_binary:
    type: 'aws esp32'
    source_dir: 'app'
    build_command: make
    binary_name: my_binary
    env_vars:
        - $TOKEN
testing:
    source_dir: 'Scenario.py'
    binary_update:
         devices:
            - $Memas
         env_vars:
            - $TOKEN
         platform: 'particle photon'
         #binary: auto
         binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
         #binary: binary/mike_binary.bin
