# code_qa:
#     type: basic

build_binary:
    type: 'particle photon'
    source_dir: 'app'
    build_command: make
    env_vars:
        - $TEST
        - $TEST
        - $MAGKAS
    binary_name: my_binary

testing:
    source_dir: 'Scenario.py'
    env_vars: 
        - $Whatever_123
        - $_xyz
    binary_update:
         devices:
            - $DEVI1
            - $DEV2
         env_vars:
            - $TOKEN
         platform: 'particle photon'
         #binary: auto
         binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
         #binary: binary/mike_binary.bin
