# # code_qa:
# #     type: basic
        
# testing:
#     source_dir: 'Scenario.py'
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#     binary_update:
#          devices:
#             - $DEVICE_1    
#          platform: 'particle photon'
#          #binary: auto
#          binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
#          #binary: binary/mike_binary.bin

# pre_flight:
#     - echo "Hello there"
#     - echo "Over"

# post_flight: 
#     - echo "Post flight command"

build_binary:
#     env_vars:
#        - $DEVICE_1
    pre_flight: 
       - echo "hello there"
       - cd ../ && echo $PWD
    builder: 'particle photon'
    binary_name: 'app/target/app.bin'
    script: echo 'hello there' && cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/app
    post_flight: 
       - echo "finito la musica"

testing:
   script: examples/long_test.py

# build_binary:
#     builder: 'platformio'
#     pre_flight:  mkdir "/tmp/build" 
#     script: platformio ci --project-conf="platformio.ini" --build-dir="/tmp/build" --keep-build-dir aws_platformio
#     binary_name: '/tmp/build/.pioenvs/esp32dev/firmware.elf'
    
# build_binary:
#     builder: 'aws esp32'
#     #pre_flight:
#     #    - bash ./thing_config.sh
#     script: 'cd esp32_devkitc_esp_wrover_kit/make && make'
#     binary_name: 'esp32_devkitc_esp_wrover_kit/build/aws_demo.bin'
#     env_vars:
#         - $SPN_AWS_ACCESS_KEY_ID
#         - $SPN_AWS_SECRET_ACCESS_KEY
#         - $SPN_AWS_OUTPUT
#         - $SPN_AWS_REGION
       
#testing:
#    script: uartTest.py
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#     device_update:
#         devices:
#             - $DEVICE_1
#         ota_method: particle
#         binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l

# testing:
#     pre_flight: echo "Test"
#     script: 'examples/long_test.py'
# #     device_update:
# #         ota_method: 'spanner shipper'
# #         env: 'production'
# #         repo: 'current'
#     post_flight: echo "done"
    
# build_binary:
#     builder: 'particle photon'
#     source: 'app'
    
#     binary_name: my_binary
#     env_vars:
#         - $SPN_AWS_ACCESS_KEY_ID
#         - $SPN_AWS_SECRET_ACCESS_KEY
#         - $SPN_ESP32_THING_NAME
#         - $SPN_ESP32_WIFI_SSID
#         - $SPN_ESP32_WIFI_PASSWORD
#         - $SPN_ESP32_WIFI_SECURITY
        
# build_binary:
#     builder: 'particle photon'
#     pre_flight: 
#        - echo "Pre flight commands"
#     script: echo 'script'
#     post_flight: 
#        - echo "done"
#        - bash -c "exit 2;"
#     binary_name: 'app/target/app.bin'

# testing:
#     pre_flight: 
#        - echo "Step 1"
#     script: 'examples/1. Basic Tests/GPIO/1. Set Digital Output/scenario.py'
#     post_flight: echo "Done"
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#     device_update:
#         devices:
#             - $DEVICE_1    
#         ota_method: 'particle'
# #         binary: auto
#         binary: https://drive.google.com/uc?export=download&id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
# #        binary: binary/mike_binary.bin
        
